version: "3.9"

networks:
  default:
    external: 
      name: my-network

services:

  prometheus:
    image: prom/prometheus:v2.23.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports:
      - 9093:9093
    restart: always

  grafana:
    image: grafana/grafana:7.3.6
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    restart: always

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    ports:
      - 9100:9100
    restart: unless-stopped